"""empty message

Revision ID: 79c4e8051436
Revises: c20689948fa9
Create Date: 2023-09-17 16:36:37.226279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c4e8051436'
down_revision: Union[str, None] = 'c20689948fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothes', sa.Column('img_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothes', 'img_path')
    # ### end Alembic commands ###
